framework:
    messenger:
        serializer:
            id: 'messenger.transport.symfony_serializer'
        buses:
            messenger.bus.default:
                middleware:
                    - 'messenger.middleware.validation'
                    - 'App\Messenger\Middleware\TransactionAllowedMiddleware'
        transports:
            sqs: 'enqueue://sqs?receiveTimeout=1000&queue[name]=%env(resolve:MESSENGER_SQS_QUEUE)%&topic[name]=%env(resolve:MESSENGER_SQS_QUEUE)%'

        routing:
            'App\Messenger\MessageInterface': sqs
