version: '3.4'

services:

  db:
    image: mysql:8
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_PASSWORD=password
      - MYSQL_USER=app_user
    volumes:
      - "mysqlvol:/var/lib/mysql"
    ports:
      - "3307:3306"

  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
    - ./:/var/www/html
    depends_on:
     - db
    networks:
     - backend

  web:
    image: nginx:latest
    ports:
    - "8888:80"
    volumes:
    - ./:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    networks:
      - backend

  localstack:
    image: localstack/localstack:latest
    networks:
      - backend
    ports:
      - '4567-4584:4567-4584'
      - '8080:8080'
    volumes:
      - ~/tmp:/tmp
    environment:
      SERVICES: "sqs"
      DATA_DIR: '/tmp/localstack/data'
      HOSTNAME_EXTERNAL: localstack

networks:
  backend:

volumes:
  mysqlvol: